<?php
/**
 * views/pages/error.php
 * Automatically catches and displays server errors
 */

// 1. Automatically grab the error code generated by the server
$error_code = $_SERVER['REDIRECT_STATUS'] ?? http_response_code();

// Fallback to 404 if it's empty or 200 (OK)
if (empty($error_code) || $error_code == 200) {
    $error_code = 404;
}

// 2. Define the messages for each error type
$errors = [
    400 => ['title' => 'Bad Request',           'desc' => 'Your browser sent a request that this server could not understand.'],
    401 => ['title' => 'Unauthorized',          'desc' => 'Authentication is required to access this page.'],
    403 => ['title' => 'Access Denied',         'desc' => 'You do not have permission to access this folder or file.'],
    404 => ['title' => 'Page Not Found',        'desc' => 'The page you\'re looking for doesn\'t exist or has been moved.'],
    405 => ['title' => 'Method Not Allowed',    'desc' => 'The requested method is not supported for this resource.'],
    500 => ['title' => 'Internal Server Error', 'desc' => 'Oops! Our server encountered a glitch. We are looking into it.'],
    502 => ['title' => 'Bad Gateway',           'desc' => 'The server received an invalid response from the upstream server.'],
    503 => ['title' => 'Service Unavailable',   'desc' => 'We are temporarily offline for maintenance. Please check back soon.'],
];

// 3. Match the exact error (or use a fallback)
$error_title = $errors[$error_code]['title'] ?? 'Unknown Error';
$error_desc  = $errors[$error_code]['desc']  ?? 'An unexpected error occurred processing your request.';

// SEO / Meta
$meta_title  = $error_code . ' – ' . $error_title;
$meta_desc   = $error_desc;
$canonical   = SITE_URL . '/';
$og_type     = 'website';
$schema_json = '';

// Ensure headers reflect the actual error code for search engines
http_response_code($error_code);
?>
<!DOCTYPE html>
<html lang="en" class="scroll-smooth bg-white">
<head>
    <?php require __DIR__ . '/../layouts/head.php'; ?>
    <meta name="robots" content="noindex, nofollow">
</head>
<body class="text-gray-900 antialiased">

<div class="flex min-h-screen flex-col items-center justify-center px-6 text-center">
    
    <!-- Automatically displays the 404, 500, 403, etc -->
    <span class="text-[120px] md:text-[200px] font-black text-gray-100 leading-none select-none" aria-hidden="true">
        <?= e($error_code) ?>
    </span>
    
    <h1 class="text-2xl md:text-4xl font-black uppercase tracking-tight text-black mb-4 -mt-6">
        <?= e($error_title) ?>
    </h1>
    <p class="text-gray-400 text-sm md:text-base font-medium mb-10 max-w-md">
        <?= e($error_desc) ?>
    </p>
    
    <div class="flex flex-col sm:flex-row gap-4">
        <?php if ($error_code != 404 && $error_code != 400): ?>
        <button onclick="window.history.back()"
           class="px-10 py-4 bg-white border-2 border-gray-100 text-gray-500 text-[10px] font-black uppercase tracking-[0.3em] hover:bg-gray-50 hover:text-black transition-all">
            Go Back
        </button>
        <?php endif; ?>
        
        <a href="<?= SITE_URL ?>/"
           class="px-10 py-4 bg-black text-white text-[10px] font-black uppercase tracking-[0.3em] hover:bg-youtube-red transition-all shadow-xl">
            Return Home
        </a>
    </div>
</div>

</body>
</html>